### ISSUE TITLE
Failure to build for AMD Ryzen + CUDA with 'error: identifier "__builtin_ia32_serialize" is undefined'

### ISSUE THREAD

**Issue by RalphSteinhagen** [taskflow/taskflow#371]
**Describe the bug**
Fails to build for AMD Ryzen, CUDA (NVIDIA RTX), and recent gcc and nvcc versions with the following compile error:
```
[ 68%] Building CUDA object examples/cuda/CMakeFiles/cuda_device_property.dir/cuda_device_property.cu.o
cd /home/steinhagen/git/taskflow/build/examples/cuda && /usr/local/cuda-11.5/bin/nvcc -forward-unknown-to-host-compiler  -I/home/steinhagen/git/taskflow -O3 -DNDEBUG --extended-lambda -Xcompiler=-Wall,-Wextra,-Wfatal-errors -MD -MT examples/cuda/CMakeFiles/cuda_device_property.dir/cuda_device_property.cu.o -MF CMakeFiles/cuda_device_property.dir/cuda_device_property.cu.o.d -x cu -c /home/steinhagen/git/taskflow/examples/cuda/cuda_device_property.cu -o CMakeFiles/cuda_device_property.dir/cuda_device_property.cu.o
/usr/lib64/gcc/x86_64-suse-linux/11/include/serializeintrin.h(41): error: identifier "__builtin_ia32_serialize" is undefined
```
The other CPU-only/non-CUDA examples seem to compile and run just fine, provided the unit tests have been disabled.  
The plain nvcc SDK installation has been verified working fine using the NVIDIA_CUDA-11.5 examples.

**To Reproduce**
tested on the main git branch [ac1a3f8f] with the following flags:
1. 'TF_BUILD_CUDA==ON' 
2. 'TF_BUILD_TESTS==OFF' (possibly another bug)

**Desktop:**
 - OS: Linux (OpenSUSE Tumbleweed)
 - gcc: 11.2.1 20211124
 - nvcc: release 11.5, V11.5.119
 - cmake version 3.22.1

Any help would be much appreciated and keep up the good work! :+1:

**Comment by RalphSteinhagen** [comment]
Hey, your recent commit 75454ae5 disabled the following lines in `os.hpp` which fixes also the above issue:

```cpp
//#if __has_include (<immintrin.h>)
//  #define TF_HAS_MM_PAUSE 1
//  #include <immintrin.h>
//#endif
```

Thanks a lot for the quick fix much appreciated! :+1:
