### ISSUE TITLE
Problem with static _per_thread

### ISSUE THREAD

**Issue by Jamaika1** [taskflow/taskflow#312]
I don't know how to combine object files in GCC. I have `_per_thread` to connect. 
```
inline static thread_local PerThread _per_thread;
```

**Comment by tsung-wei-huang** [comment]
would you please be a bit specific about your question?

**Comment by Jamaika1** [comment]
```
c:/msys1101/bin/../lib/gcc/x86_64-w64-mingw32/11.0.1/../../../../x86_64-w64-mingw32/bin/ld.exe: BufferedStream.o:BufferedStream.cpp:(.text+0x20a0): multiple definition of `TLS init function for tf::Executor::_per_thread'; BitIO.o:BitIO.cpp:(.text+0x1c90): first defined here
```

**Comment by tsung-wei-huang** [comment]
what is the version of your gcc?

**Comment by Jamaika1** [comment]
GCC 11.0.1. I wonder how taskflow works.

**Comment by tsung-wei-huang** [comment]
What version of taskflow do you use?

**Comment by Jamaika1** [comment]
https://github.com/taskflow/taskflow/commit/0cded15eb3d4de73f266bbe15f91a2c68faf5642

**Comment by tsung-wei-huang** [comment]
Could you please use the newest master branch and see if the problem is still there? I suspect this a specific compiler error on the MS platform.

**Comment by Jamaika1** [comment]
Bug fixed ee07279. I was able to compile in gcc 11.0.1.

Thanks

**Comment by tsung-wei-huang** [comment]
@Jamaika1 thanks for bringing this up

**Comment by Pentalimbed** [comment]
I'm using latest WinLibs which uses gcc 11.1.0 and MinGW 8.0.2, but I got the same error building with VSCode and CMake...
