### ISSUE TITLE
Multiple compilation error with utilities (uuid and object_pool) after v2.2.0

### ISSUE THREAD

**Issue by remz1337** [taskflow/taskflow#256]
Unable to compile my project after upgrading from v2.2.0 to v2.7.0 when including CSV2 library before

**To Reproduce**
1. Write a simple "Hello World" C++ console program
2. Include CSV2 library (https://github.com/p-ranav/csv2)
3. Include Taskflow library

`#include <iostream>`
`#include <csv2/reader.hpp>`
`#include <taskflow/taskflow.hpp>`
`int main(int argc, char** argv){`
`	std::cout << "hello" << std::endl;`
`	return 0;`
`}`

This program throws a bunch of compilation errors with uuid.hpp and object_pool.hpp only after upgrading v2.2.0 to v2.7.0. Swapping the includes solves the issue so it must be some redefinition or something. The full error list is listed below:

Severity	Code	Description	File	Line	Suppression State
Error	C2059	syntax error: ')'	utility\uuid.hpp	78	
Error	C2589	'(': illegal token on right side of '::'	utility\uuid.hpp	78	
Error	C2143	syntax error: missing ',' before '?'	utility\uuid.hpp	78	
Error	C4430	missing type specifier - int assumed. Note: C++ does not support default-int	utility\uuid.hpp	78	
Error	C2059	syntax error: '?'	utility\uuid.hpp	78	
Error	C2589	'(': illegal token on right side of '::'	utility\uuid.hpp	79	
Error	C2059	syntax error: ')'	utility\uuid.hpp	80	
Error	C2660	'distribution': function does not take 1 arguments	utility\uuid.hpp	83	
Error	C3536	'random_value': cannot be used before it is initialized	utility\uuid.hpp	86	
Error	C2660	'distribution': function does not take 1 arguments	utility\uuid.hpp	86	
Error	C2589	'(': illegal token on right side of '::'	utility\object_pool.hpp	68	
Error	C2062	type 'unknown-type' unexpected	utility\object_pool.hpp	68	
Error	C2737	'private: static unsigned int const tf::ObjectPool<tf::Node,65536>::X': 'constexpr' object must be initialized utility\object_pool.hpp	68	
Error	C2059	syntax error: ')'	utility\object_pool.hpp	68	
Error	C2131	expression did not evaluate to a constant	utility\object_pool.hpp	71	
Error	C2131	expression did not evaluate to a constant	utility\object_pool.hpp	74	
Error	C2131	expression did not evaluate to a constant	utility\object_pool.hpp	82	

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v2.7.0
 - CMake project
 - VCPKG for package management (CSV2 and Taskflow installed through this)

**Comment by tsung-wei-huang** [comment]
Hi, @remz1337 , how did you compile the testcode ? I tried doing the same with on my machine and there is no problem. Also no problem for gcc on Linux

```
g++ test.cpp -I ../taskflow -I ../csv2/include/ -std=c++17
```

**Comment by remz1337** [comment]
hmm can you try to include csv2 before taskflow? I only get the errors when they are included in that specific order. If it still works then I guess it would be something related to Windows/Visual Studio

**Comment by tsung-wei-huang** [comment]
Yes, I tried both and they work. Did you enable c++17 (for master branch) or c++14 (for 2.7)?

**Comment by remz1337** [comment]
Yes, tested with c++ 14 and 17, still same errors. Do you have a way to test with MSVC?

**Comment by tsung-wei-huang** [comment]
@remz1337 I will try it in our university machine tomorrow which comes with an MSVC compiler. 

The error message looks very strange. I suspect it's due to some disorganization of the compiler setting.

**Comment by tsung-wei-huang** [comment]
Is this problem still there with the new master branch?

**Comment by remz1337** [comment]
Just tested with v3.0 from vcpkg and the issue seems resolved! Thank you
