### ISSUE TITLE
flow_builder.hpp:674:10: error: ‘tf::Task tf::FlowBuilder::transform_reduce(B, E, T&, BOP, UOP) is used but never defined

### ISSUE THREAD

**Issue by foolnotion** [taskflow/taskflow#375]
**Describe the bug**
After updating taskflow to 3.3 my code does not compile anymore.

g++ error:
```
flow_builder.hpp:674:10: error: ‘tf::Task tf::FlowBuilder::transform_reduce(B, E, T&, BOP, UOP) is used but never defined [-fpermissive]
```

clang++ error:
```
flow_builder.hpp:674:10: error: ‘tf::Task tf::FlowBuilder::transform_reduce(B, E, T&, BOP, UOP) is used but not defined in this translation unit, and cannot be defined in any other translation unit because its type does not have linkage
```

**To Reproduce**
1. update to taskflow 3.3
2. try to compile some code that uses taskflow.transform_reduce

**Additional context**
The same error occurs regardless whether I try to compile my library statically or dynamically.

**Comment by tsung-wei-huang** [comment]
@foolnotion thanks for bringing this up. As mentioned in the breaking change of the [release notes](https://taskflow.github.io/taskflow/release-3-3-0.html), you will need to separately include the header file of the algorithm:

```cpp
#include <taskflow/algorithm/reduce.hpp>
```

We made this change in order to reduce compile time caused by unnecessary code.

**Comment by foolnotion** [comment]
@tsung-wei-huang  Thanks for the quick reply! I should have read the release notes more carefully.

**Comment by tsung-wei-huang** [comment]
@foolnotion no problem. Thanks for your interest and use in Taskflow.
