### ISSUE TITLE
for_each.hpp(144,15): error C3848: expression having type 'const C' would lose some const-volatile qualifiers

### ISSUE THREAD

**Issue by olologin** [taskflow/taskflow#673]
The following code is impossible to compile with taskflow 3.9 anymore, because of capture-by-reference to capture-by-value changes in https://github.com/taskflow/taskflow/commit/4b815ba01e62443c7fd9978c873ed6bacbf3a805#diff-456f14b7ccb0772b1d759244de1dca9851b74f0e2879ac0185987320b916eeaa

```
struct DoTask
{
	void operator()(int i) { printf("%d, ", i); }
};

DoTask t;

::tf::Executor ex(4);
tf::Taskflow taskflow;
taskflow.for_each_index(
	0,
	100,
	1,
	t);

ex.run(taskflow).get(); // taskflow/algorithm/for_each.hpp(144,15): error C3848: expression having type 'const C' would lose some const-volatile qualifiers in order to call 'void TestBody::DoTask::operator ()(int)'
```

Compiler:  Visual studio 19 (MSVC 19.29.30159)

**Comment by tsung-wei-huang** [comment]
Thank you for the catch. Indeed there was a miss in placing `mutable` after the lambda of for-each. I have fixed it and pushed it to the main branch. Can you try the it again?

**Comment by olologin** [comment]
@tsung-wei-huang yes, it helps. I think in transform.hpp similar change should be applied.

**Comment by tsung-wei-huang** [comment]
Yes, I just made another push to the main/dev that resolved this `mutable` issue. Please don't hesitate to let me know if you still observe any issues. Thanks!
